package component:books-api-dep@0.1.0;

interface books {
    get-books: func() -> list<book>;
    get-book: func(id: u32) -> book;

    record book {
        name: string,
        author: string,
        description: string
    }
}