apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-wasi-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs-wasi-console
  template:
    metadata:
      labels:
        app: cs-wasi-console
    spec:
      runtimeClassName: spin-test
      containers:
        - name: app
          image: mrhockeymonkey/cs-wasi-console:latest
          command: ["/"]
          resources: # limit the resources to 128Mi of memory and 100m of CPU
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cs-wasi-console
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: cs-wasi-console
---
# Middleware
# Strip prefix /spin
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /spin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wasm-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: default-strip-prefix@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /spin
            pathType: Prefix
            backend:
              service:
                name: cs-wasi-console
                port:
                  number: 80